### ISSUE TITLE
Push Dropzone-gwt to Maven Central

### ISSUE THREAD

**Issue by andrezimmermann** [andrezimmermann/dropzone-gwt#11]

**Comment by OrNot** [comment]
is there any schedule ?

**Comment by andrezimmermann** [comment]
Tomorrow maybe, already have the OSS repo created, just need to sign and push the artifacts there.

**Comment by andrezimmermann** [comment]
This was harder than I though!

But can you try this? 

<dependency>
  <groupId>com.github.andrezimmermann</groupId>
  <artifactId>dropzone-gwt</artifactId>
  <version>0.0.4</version>
</dependency>
