### ISSUE TITLE
No source code is available for type com.github.andrezimmermann.dropzone.client.Dropzone

### ISSUE THREAD

**Issue by OrNot** [andrezimmermann/dropzone-gwt#12]
I did include the line:

<inherits name="com.github.andrezimmermann.Dropzone" />

I missed something?

**Comment by OrNot** [comment]
I figured out the cause:  the source code path should be "/dropzone/client" but not "client" by default.

**Comment by andrezimmermann** [comment]
Thanks,  I will take a look into this soon!
