### ISSUE TITLE
Parse the css error 

### ISSUE THREAD

**Issue by OrNot** [andrezimmermann/dropzone-gwt#13]
com.google.gwt.thirdparty.common.css.compiler.ast.GssParserException: Parse error in [auto-converted gss files from : [file:/C:/dropzone-gwt/src/main/java/com/github/andrezimmermann/dropzone/client/injector/resources/css/dropzone.css]] at line 401 column 1:
@
^

at com.google.gwt.thirdparty.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:190)
at com.google.gwt.thirdparty.common.css.compiler.ast.GssParser.parse(GssParser.java:46)
....

Caused by: com.google.gwt.thirdparty.common.css.compiler.ast.ParseException: Encountered " <BAD_TOKEN> "@ "" at line 401, column 1.

**Comment by andrezimmermann** [comment]
You have  <set-configuration-property name="CssResource.enableGss" value="true"> somewhere in your app module? It looks like it is trying to parse as GSS. That have a different syntax as CSS. I will look into it, maybe convert the CSS as GSS. Or try a way where both can co-exist :)

**Comment by andrezimmermann** [comment]
Looking at the CSS file, seems eclipse broke the formatting leaving a invalid @-moz-keyframes declaration :(

**Comment by OrNot** [comment]
I don't do anything after importing maven project from github. The original file has the same symbols .

**Comment by andrezimmermann** [comment]
Fixed with commit 6912fe942bf4b277530836d6dde188f0ee07cfa3
