### ISSUE TITLE
How to handle a added file 

### ISSUE THREAD

**Issue by OrNot** [andrezimmermann/dropzone-gwt#16]
I want to remove the invalid file as below

new DropzoneEventHandler(){

			@Override
			public void onAddedFile(File file)
			{
                             if(!isValid(file)){
                             
                              dropzone.removeFile(file);
                            }
               		}

}

but the removeFile 's argument is int type, not File type,  is there any other way to remove it ?

**Comment by andrezimmermann** [comment]
Darn, there isn't a removeFile(File) or a getFileIndex(File) that return the index. I will code both soon, thank you for you patience.

**Comment by OrNot** [comment]
wow... thanks for your quick response. 

Off the topic, is there any way to read the file  passed in with GWT?

**Comment by andrezimmermann** [comment]
Yeah, you can! Dropzone.js use the File API, you will need to wrap the browser [FileReader](https://w3c.github.io/FileAPI/#filereader-interface) and then call one of the read methods, returning a wrapped ByteArray or whatever is your need! Check [here](http://www.html5rocks.com/en/tutorials/file/dndfiles/), it gives examples on how to do it.
